/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MystatsRouteImport } from './routes/mystats'
import { Route as NginxRouteImport } from './routes/nginx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MystatsRoute = MystatsRouteImport.update({
  id: '/mystats',
  path: '/mystats',
  getParentRoute: () => rootRouteImport,
} as any)
const NginxRoute = NginxRouteImport.update({
  id: '/nginx',
  path: '/nginx',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mystats': typeof MystatsRoute
  '/nginx': typeof NginxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mystats': typeof MystatsRoute
  '/nginx': typeof NginxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mystats': typeof MystatsRoute
  '/nginx': typeof NginxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mystats' | '/nginx'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mystats' | '/nginx'
  id: '__root__' | '/' | '/mystats' | '/nginx'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MystatsRoute: typeof MystatsRoute
  NginxRoute: typeof NginxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mystats': {
      id: '/mystats'
      path: '/mystats'
      fullPath: '/mystats'
      preLoaderRoute: typeof MystatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nginx': {
      id: '/nginx'
      path: '/nginx'
      fullPath: '/nginx'
      preLoaderRoute: typeof NginxRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MystatsRoute: MystatsRoute,
  NginxRoute: NginxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
